---
task_retries: 3
task_delay: 5

## Repos
rpmfusion_free_key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
rpmfusion_nonfree_key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}
rpmfusion_free_rpm: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
rpmfusion_nonfree_rpm: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
flatpak_repo: https://dl.flathub.org/repo/flathub.flatpakrepo

## Packages to install or remove
packages:
  install:
    # Archiving
    - p7zip
    - p7zip-plugins

    # Cloud
    #- owncloud-client

    # Images
    #- gimp
    #- inkscape

    # Device support
    - akmods
    - cups-bjnp
    - dkms
    #- epson-inkjet-printer-escpr # support for recent Epson inkjet printers
    #- hpijs
    #- hplip # support for extra HP printers
    - kernel-devel
    #- libsane-hpaio # support for extra HP scanners
    #- libva-intel-driver # HW video decode for intel
    - lm_sensors-sensord
    - memtest86+
    - pptp-setup
    - sane-backends
    - sane-backends-drivers-cameras
    - sane-backends-drivers-scanners
    #- spice-server
    #- spice-vdagent
    #- splix

    # Filesystems
    - btrfs-progs
    - exfat-utils
    - fuse
    - fuse-exfat
    - gparted

    # Fonts
    - open-sans-fonts
    - google-droid-sans-mono-fonts
    - mozilla-fira-mono-fonts

    # Multimedia
    #- HandBrake-gui
    - alsa-plugins-pulseaudio
    - alsa-utils
    - ffmpegthumbnailer
    - flac
    #- gphoto2 #for camera support in shotwell
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - gstreamer1-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-extras
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-ugly
    - lame
    - libaacs
    - libbluray
    - libdvdnav
    - libdvdread
    - libvpx-utils
    - pavucontrol
    - raw-thumbnailer
    - shotwell
    - vlc
    - vlc-extras
    - vorbis-tools

    # Office/Productivity Suite
    #- "@libreoffice"
    #- libreoffice-langpack-en
    #- libreoffice-ogltrans
    #- libreoffice-opensymbol-fonts
    #- libreoffice-pdfimport
    #- libreoffice-ure
    #- libreoffice-xsltfilter

    # Package Management
    - PackageKit-gstreamer-plugin
    - dnf-plugin-system-upgrade
    - dnf-plugins-core
    - python3-dnf-plugin-tracer

    # System/Development
    - android-tools
    - aspell-en
    - chrony
    - cowsay
    - "@c-development"
    - "@development-tools"
    - expect
    - fdupes
    - fpaste
    - fprintd-pam
    - frei0r-plugins
    - gcc
    - g++
    - git
    - htop
    - mlocate
    - ntfsprogs
    - powertop
    - pybluez
    - redhat-lsb-core
    - vim

    # System Administration/Configuration
    - firewall-config
    - fonts-tweak-tool
    - liveusb-creator
    - policycoreutils-gui
    - screen
    - screenfetch
    - setools-console
    - tmux

    # Terminal Enhancements
    - bash-completion
    #- PackageKit-command-not-found

    # Web
    #- firefox
  remove:
    - abrt
